/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 lighthouse.glb --types --shadows --transform --keepmaterials 
Files: lighthouse.glb [196.79KB] > /home/alexkahn/alex/portfolio/src/assets/glb/lighthouse-transformed.glb [23.39KB] (88%)
*/
import { Mesh, MeshStandardMaterial, Vector3 } from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { animated, useSpring } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    Lighthouse1: Mesh;
  };
  materials: {
    lambert2SG: MeshStandardMaterial;
  };

  // @ts-expect-error: gltfjsx 6.4.1 has error in types
  animations: GLTFAction[];
};

export const LighthouseModel = (props: JSX.IntrinsicElements["group"]) => {
  let baseScale = 1;

  if (props.scale instanceof Vector3) {
    baseScale = props.scale.x;
  } else if (typeof props.scale === "number") {
    baseScale = props.scale;
  }

  const [modelSpring, modelApi] = useSpring(() => ({
    scale: baseScale,
    config: { mass: 1, tension: 280, friction: 60, duration: 300 },
  }));

  const handleModelHover = () => {
    modelApi.start({
      scale: baseScale * 1.1,
    });
  };

  const handleModelUnhover = () => {
    modelApi.start({ scale: baseScale });
  };

  const handleModelClick = () => {
    // You can define any click handling logic here
  };

  const { nodes, materials } = useGLTF(
    "/lighthouse-transformed.glb",
  ) as GLTFResult;
  return (
    <animated.group
      {...props}
      dispose={null}
      {...modelSpring}
      onPointerOver={handleModelHover}
      onPointerOut={handleModelUnhover}
      onClick={handleModelClick}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lighthouse1.geometry}
        material={materials.lambert2SG}
      />
    </animated.group>
  );
};

useGLTF.preload("/lighthouse-transformed.glb");
